#include <bits/stdc++.h>

using namespace std;

int main()

{

 int a,b,c;
  cin>>a>>b>>c;

  if(a>=b and a>=c)
     cout<<a;

  else if(b>=a and b>=c)
      cout<<b;

  else 
    cout<< c;
            
        
    return 0;
}

     

// //  string s;

// //  getline(cin,s);

// //  cout<<s;
// int a ;
// cin>>a;

// if(a==1)
// {
//     cout<<"mon";
// }
// else if (a==2)
// {
//     cout<<"tuesday";
// }
// else if (a==3)
// {
//     cout<<"wednesday";
// }

// else if(a==4)
// {
//     cout<<"thrusday";

// }
// else if (a==5)
// {
//     cout<<"friday";
// }
// else {

//     cout<<"saturday";
// }







