#include <bits/stdc++.h>

using namespace std;




int main(){

{
    extern int i;

    cout<<i<<"";

    {
        int i =10;

        cout<<i<<"";
        
    }
}
// //  string s;

// //  getline(cin,s);

// //  cout<<s;
// int a ;
// cin>>a;

// if(a==1)
// {
//     cout<<"mon";
// }
// else if (a==2)
// {
//     cout<<"tuesday";
// }
// else if (a==3)
// {
//     cout<<"wednesday";
// }

// else if(a==4)
// {
//     cout<<"thrusday";

// }
// else if (a==5)
// {
//     cout<<"friday";
// }
// else {

//     cout<<"saturday";
// }



 return 0;
}


